# Generated by Django 2.1 on 2019-05-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveypublic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsurveytemplatefield',
            name='retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defaultsurveytemplatefield',
            name='type',
            field=models.ForeignKey(limit_choices_to={'survey': True}, on_delete=django.db.models.deletion.CASCADE, to='geometriespublic.FieldType'),
        ),
    ]
