# Generated by Django 2.1 on 2019-06-26 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geometriespublic', '0009_auto_20190528_1151'),
        ('surveypublic', '0003_add_default_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSurveyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feature_codes', models.ManyToManyField(blank=True, related_name='master_survey_templates', to='geometriespublic.FeatureCode')),
            ],
        ),
        migrations.CreateModel(
            name='MasterSurveyTemplate_Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Master Survey Template Fields',
            },
        ),
        migrations.AddField(
            model_name='defaultsurveytemplatefield',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mastersurveytemplate_field',
            name='defaultsurveytemplatefield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveypublic.DefaultSurveyTemplateField'),
        ),
        migrations.AddField(
            model_name='mastersurveytemplate_field',
            name='mastersurveytemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_survey_template_fields', to='surveypublic.MasterSurveyTemplate'),
        ),
        migrations.AddField(
            model_name='mastersurveytemplate',
            name='fields',
            field=models.ManyToManyField(through='surveypublic.MasterSurveyTemplate_Field', to='surveypublic.DefaultSurveyTemplateField'),
        ),
    ]
