# Generated by Django 2.1 on 2019-06-27 08:24

from django.db import migrations, connection

def update_content_type(apps, schema_editor):
    """
    Swap content type models. This keeps generic relationships correct.
    """
    
    if connection.schema_name == 'public':
        ContentType = apps.get_model("contenttypes", "ContentType")
        
        obj = ContentType.objects.get(app_label='surveypublic', model='publicsurveytemplatefield')
        obj.model = 'publicsurveytemplatefield2'
        obj.save()
        
        obj = ContentType.objects.get(app_label='surveypublic', model='defaultsurveytemplatefield')
        obj.model = 'publicsurveytemplatefield'
        obj.save()
        
        obj = ContentType.objects.get(app_label='surveypublic', model='publicsurveytemplatefield2')
        obj.model = 'defaultsurveytemplatefield'
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geometriespublic', '0009_auto_20190528_1151'),
        ('surveypublic', '0004_auto_20190626_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultSurveyTemplateField',
            new_name='PublicSurveyTemplateField',
        ),
        migrations.RenameField(
            model_name='mastersurveytemplate_field',
            old_name='defaultsurveytemplatefield',
            new_name='publicsurveytemplatefield',
        ),
        migrations.RunPython(
            code=update_content_type,
        ),
    ]
