# Generated by Django 2.1 on 2019-06-27 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveypublic', '0005_auto_20190627_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicsurveytemplatefield',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
    ]
