# Generated by Django 2.1 on 2019-05-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geometriespublic', '0002_auto_20190409_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttributeType',
            new_name='FieldType',
        ),
        migrations.AlterModelOptions(
            name='featurecode',
            options={'ordering': ['display_name', 'pk']},
        ),
    ]
