# Generated by Django 2.1 on 2019-05-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geometriespublic', '0003_auto_20190517_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='attributes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='survey',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publicattribute',
            name='type',
            field=models.ForeignKey(limit_choices_to={'survey_only': False}, on_delete=django.db.models.deletion.CASCADE, to='geometriespublic.FieldType'),
        ),
    ]
