# Generated by Django 2.1 on 2019-05-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geometriespublic', '0005_add_field_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicattribute',
            name='type',
            field=models.ForeignKey(limit_choices_to={'attributes': True}, on_delete=django.db.models.deletion.CASCADE, to='geometriespublic.FieldType'),
        ),
    ]
