# Generated by Django 2.1 on 2019-05-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometriespublic', '0006_auto_20190520_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='label',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='type_name',
            field=models.CharField(default='temp', max_length=20),
            preserve_default=False,
        ),
    ]
