# Generated by Django 2.1 on 2019-05-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometriespublic', '0008_modify_field_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='label',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
