# Generated by Django 2.1 on 2019-06-27 11:15

from django.db import migrations, connection


def modify_field_types(apps, schema_editor):
    """
    Add new 'select' FieldType and change 'Condition' foreignkeys to 'Select'
    """
    FieldType = apps.get_model("geometriespublic", "FieldType")
    
    try:
        condition = FieldType.objects.get(name='condition')
        
        # I can't actually delete condition here as it has relationships with tenants
        condition.survey = False
        condition.label = "The record can be deleted."
        condition.save()
        
        select,created = FieldType.objects.get_or_create(name='select', label='Select', type_name='char')

        if connection.schema_name == 'public':
            PublicSurveyTemplateField = apps.get_model("surveypublic", "PublicSurveyTemplateField")
            fields = PublicSurveyTemplateField.objects.filter(type=condition)
            
            for field in fields:
                field.type = select
                field.save()
        else:
            SiteSurveyTemplateField = apps.get_model("survey", "SiteSurveyTemplateField")
            fields = SiteSurveyTemplateField.objects.filter(type=condition)
            
            for field in fields:
                field.type = select
                field.save()
    except:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('geometriespublic', '0009_auto_20190528_1151'),
    ]

    operations = [
        migrations.RunPython(
            code=modify_field_types,
        ),
    ]
