# Generated by Django 2.1 on 2019-09-06 10:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bgsite', '0035_auto_20190722_1416'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_edit_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('name', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('booking_buffer_duration', models.IntegerField(default=0, help_text='Minimum length of time between other bookings in this category')),
                ('simultaneous_bookings', models.IntegerField(blank=True, help_text='Number of bookings in this category that can take place simultaneously', null=True)),
                ('max_booking_per_day', models.IntegerField(blank=True, help_text='Maximum number of bookings in this category that can take place on one day', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('default_duration', models.IntegerField(default=60, verbose_name='Default duration of event in minutes')),
                ('event_earliest_time_mon', models.TimeField(blank=True, default=datetime.time(10, 0), null=True, verbose_name='Earliest start time: Monday')),
                ('event_latest_time_mon', models.TimeField(blank=True, default=datetime.time(16, 0), null=True, verbose_name='Latest end time: Monday')),
                ('event_earliest_time_tue', models.TimeField(blank=True, default=datetime.time(10, 0), null=True, verbose_name='Earliest start time: Tuesday')),
                ('event_latest_time_tue', models.TimeField(blank=True, default=datetime.time(16, 0), null=True, verbose_name='Latest end time: Tuesday')),
                ('event_earliest_time_wed', models.TimeField(blank=True, default=datetime.time(10, 0), null=True, verbose_name='Earliest start time: Wednesday')),
                ('event_latest_time_wed', models.TimeField(blank=True, default=datetime.time(16, 0), null=True, verbose_name='Latest end time: Wednesday')),
                ('event_earliest_time_thu', models.TimeField(blank=True, default=datetime.time(10, 0), null=True, verbose_name='Earliest start time: Thursday')),
                ('event_latest_time_thu', models.TimeField(blank=True, default=datetime.time(16, 0), null=True, verbose_name='Latest end time: Thursday')),
                ('event_earliest_time_fri', models.TimeField(blank=True, default=datetime.time(10, 0), null=True, verbose_name='Earliest start time: Friday')),
                ('event_latest_time_fri', models.TimeField(blank=True, default=datetime.time(16, 0), null=True, verbose_name='Latest end time: Friday')),
                ('event_earliest_time_sat', models.TimeField(blank=True, default=datetime.time(10, 0), null=True, verbose_name='Earliest start time: Saturday')),
                ('event_latest_time_sat', models.TimeField(blank=True, default=datetime.time(16, 0), null=True, verbose_name='Latest end time: Saturday')),
                ('event_earliest_time_sun', models.TimeField(blank=True, default=datetime.time(10, 0), null=True, verbose_name='Earliest start time: Sunday')),
                ('event_latest_time_sun', models.TimeField(blank=True, default=datetime.time(16, 0), null=True, verbose_name='Latest end time: Sunday')),
                ('event_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemeteryadmin.EventCategory')),
            ],
        ),
        migrations.CreateModel(
            name='FuneralEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('calendar_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funeral_event', to='cemeteryadmin.CalendarEvents')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bgsite.Person')),
            ],
        ),
        migrations.AddField(
            model_name='calendarevents',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cemeteryadmin.EventType'),
        ),
        migrations.AddField(
            model_name='calendarevents',
            name='last_edit_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_calendar_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
