# Generated by Django 2.1 on 2019-09-06 10:27

from django.db import migrations
from cemeteryadmin.migrations.initial_data.initial_data import initial_event_categories


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_event_categories),
    ]
