# Generated by Django 2.1 on 2019-09-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0002_auto_20190906_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'Event categories'},
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='simultaneous_bookings',
            field=models.IntegerField(default=0, help_text='Number of bookings in this category that can take place simultaneously (including any buffer)'),
        ),
    ]
