# Generated by Django 2.1 on 2019-09-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0036_death_death_place'),
        ('cemeteryadmin', '0004_auto_20190913_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralevent',
            name='burial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bgsite.Burial'),
        ),
    ]
