# Generated by Django 2.1 on 2019-09-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0005_funeralevent_burial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralevent',
            name='checklist',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
