# Generated by Django 2.1 on 2019-09-27 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0006_funeralevent_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cemeteryadmin_calendarevents_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarevents',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevents',
            name='last_edit_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cemeteryadmin_calendarevents_last_edit_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarevents',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
