# Generated by Django 2.1 on 2019-09-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_funeraldirector'),
        ('cemeteryadmin', '0007_auto_20190927_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralevent',
            name='funeral_director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.FuneralDirector'),
        ),
    ]
