# Generated by Django 2.1 on 2019-10-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0008_funeralevent_funeral_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funeralevent',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Provisional'), (1, 'Pending'), (2, 'Declined'), (3, 'Pre-Burial Checks'), (4, 'Awaiting Burial'), (5, 'Post-Burial Checks'), (6, 'Completed')], default=0),
        ),
    ]
