# Generated by Django 2.1 on 2019-10-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0009_auto_20191002_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funeralevent',
            old_name='checklist',
            new_name='preburial_checklist',
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='postburial_checklist',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
