# Generated by Django 2.1 on 2019-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0010_auto_20191002_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeralevent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Provisional'), (1, 'Pending'), (2, 'Pre-Burial Checks'), (3, 'Awaiting Burial'), (4, 'Post-Burial Checks'), (5, 'Completed'), (6, 'Declined'), (7, 'Cancelled')], default=0),
        ),
    ]
