# Generated by Django 2.1 on 2019-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0011_auto_20191004_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralevent',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
