# Generated by Django 2.1 on 2021-04-12 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0015_calendarevents_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreburialCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grave_details', models.DateTimeField()),
                ('grave_on_ground', models.DateTimeField()),
                ('notice_of_interment', models.DateTimeField()),
                ('burial_certificate', models.DateTimeField()),
                ('noi_details', models.DateTimeField()),
                ('burial_grant_noi', models.DateTimeField()),
                ('indemnity', models.DateTimeField()),
                ('gravedigger', models.DateTimeField()),
                ('signed_off', models.DateTimeField()),
                ('invoice', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='preburial_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cemeteryadmin.PreburialCheck'),
        ),
    ]
