# Generated by Django 2.1 on 2021-04-18 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0017_auto_20210415_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeralevent',
            name='funeral_director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bgsite.Official'),
        ),
    ]
