# Generated by Django 2.1 on 2021-04-22 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0018_auto_20210418_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeralevent',
            name='preburial_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cemeteryadmin.PreburialCheck'),
        ),
    ]
