# Generated by Django 2.1 on 2021-04-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0019_auto_20210422_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeralevent',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
