# Generated by Django 2.1 on 2021-04-30 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0020_auto_20210429_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostburialCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backfill_completed', models.DateTimeField(null=True)),
                ('plot_inspected', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='postburial_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cemeteryadmin.PostburialCheck'),
        ),
    ]
