# Generated by Django 2.1 on 2021-05-04 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0021_auto_20210430_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelburial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('cancel_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='funeralevent',
            name='Cancelburial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cemeteryadmin.Cancelburial'),
        ),
    ]
