# Generated by Django 2.2.9 on 2022-01-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0023_auto_20210504_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='postburialcheck',
            name='backfill_completed_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postburialcheck',
            name='plot_inspected_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preburialcheck',
            name='burial_certificate_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preburialcheck',
            name='burial_grant_noi_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preburialcheck',
            name='grave_details_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preburialcheck',
            name='grave_on_ground_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preburialcheck',
            name='gravedigger_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preburialcheck',
            name='indemnity_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preburialcheck',
            name='invoice_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preburialcheck',
            name='noi_details_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preburialcheck',
            name='notice_of_interment_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preburialcheck',
            name='signed_off_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
