# Generated by Django 2.2.9 on 2022-01-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0025_settings'),
        ('cemeteryadmin', '0024_auto_20220118_1454'),        
    ]

    operations = [
    ]
