# Generated by Django 2.2.9 on 2022-01-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0070_meetinglocation'),
        ('cemeteryadmin', '0027_meetinglocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralevent',
            name='meeting_location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting', to='bgsite.MeetingLocation'),
        ),
    ]
