# Generated by Django 2.2.9 on 2022-01-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0031_funeralevent_meeting_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funeralevent',
            old_name='meeting_location_id',
            new_name='meeting_location',
        ),
    ]
