# Generated by Django 2.2.9 on 2022-02-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0032_auto_20220127_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'settings'},
        ),
        migrations.AddField(
            model_name='calendarevents',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
