# Generated by Django 2.2.9 on 2022-03-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0033_auto_20220209_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingLocation',
        ),
    ]
