# Generated by Django 2.2.9 on 2022-07-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0076_auto_20220613_1936'),
        ('cemeteryadmin', '0034_delete_meetinglocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralevent',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bgsite.ReservedPlot'),
        ),
    ]
