# Generated by Django 2.2.9 on 2022-09-13 16:20

from django.db import migrations

def populate_calsettings(apps, schema_editor):
    Settings = apps.get_model('cemeteryadmin', 'Settings')
    json = '{"allDaySlot":false,"initialView":"timeGridWeek","slotMaxTime":"20:00:00","slotMinTime":"09:00:00","slotDuration":"00:30:00","borderColor.pre":"orange","borderColor.post":"blue","borderColor.cancel":"gray","borderColor.default":"black","borderColor.awaiting":"red","borderColor.complete":"green","backgroundColor.cancel":"light-gray","backgroundColor.default":"purple"}'
    if Settings.objects.filter(name='calendar').exists():
        return True
    else:
        new_entry = Settings(name='calendar', preferences=json)
        new_entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cemeteryadmin', '0035_funeralevent_reservation'),
    ]

    operations = [
        migrations.RunPython(code=populate_calsettings, reverse_code=migrations.RunPython.noop),
    ]
