# Generated by Django 2.1 on 2019-05-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geometries', '0004_auto_20190416_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureattributes',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={models.Q(models.Q(('app_label', 'geometriespublic'), ('model', 'publicattribute')), models.Q(('app_label', 'geometries'), ('model', 'attribute')), _connector='OR')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
