# Generated by Django 2.1 on 2019-05-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geometries', '0005_auto_20190502_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topopoints',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='topopolygons',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='topopolylines',
            name='attributes',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
