# Generated by Django 2.1 on 2019-05-15 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geometriespublic', '0003_auto_20190517_0904'),
        ('geometries', '0006_auto_20190515_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('feature_codes', models.ManyToManyField(related_name='attributes', to='geometriespublic.FeatureCode')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geometriespublic.FieldType')),
            ],
        ),
    ]
