# Generated by Django 2.1 on 2019-05-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geometries', '0007_attribute'),
        ('geometriespublic', '0003_auto_20190517_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.ForeignKey(limit_choices_to={'attributes': True}, on_delete=django.db.models.deletion.CASCADE, to='geometriespublic.FieldType'),
        ),
    ]
