# Generated by Django 2.1 on 2019-07-12 14:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geometries', '0009_attribute_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('auto_update', models.BooleanField(default=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_cache', to='geometries.Layer')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='layercache',
            unique_together={('layer', 'auto_update')},
        ),
    ]
