# Generated by Django 2.1 on 2019-07-19 10:07

from django.db import migrations, models, connection

""" Populate min & max resolutions using public schema """
def populate_resolutions(apps, schema_editor):

    if connection.schema_name != 'public':
        
        Layer = apps.get_model("geometries", "Layer")
        FeatureCode = apps.get_model("geometriespublic", "FeatureCode")
        
        layers = Layer.objects.all()
        
        for layer in layers:
            feature_code = FeatureCode.objects.get(id=layer.feature_code_id)
            layer.min_resolution = feature_code.min_resolution
            layer.max_resolution = feature_code.max_resolution
            layer.save()
            
def reverse_populate_resolutions(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('geometries', '0009_layercache'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='max_resolution',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='min_resolution',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=populate_resolutions,
            reverse_code=reverse_populate_resolutions,
            atomic=True,
        ),
    ]
