import axios from "axios";

/**
 * Setting up request library(axios) globally
 */
export default function() {
    // Taking the CSRF Token generated by backend and added in a hidden input
    const token = (document.getElementsByName("csrfmiddlewaretoken")[0]).value;

    axios.defaults.headers.post["X-CSRFToken"] = token;
    axios.defaults.headers.put["X-CSRFToken"] = token;
    axios.defaults.headers.delete["X-CSRFToken"] = token;
    axios.defaults.headers.patch["X-CSRFToken"] = token;
    axios.defaults.withCredentials = true;
}
