# Generated by Django 2.1 on 2019-06-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0031_auto_20190404_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='age_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age(minutes)'),
        ),
    ]
