# Generated by Django 2.1 on 2019-07-01 12:58

from django.db import migrations, models, connection


def add_image_type(apps, schema_editor):

    ImageType = apps.get_model("main", "ImageType")
    ImageType.objects.get_or_create(image_type='ownership_register')


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0032_death_age_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravedeed',
            name='images',
            field=models.ManyToManyField(to='bgsite.Image'),
        ),
        migrations.RunPython(
            code=add_image_type,
            reverse_code=None,
            atomic=True,
        ),
    ]
