# Generated by Django 2.1 on 2019-09-18 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0036_death_death_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burial',
            name='graveplot',
            field=models.ForeignKey(help_text='Multiple people buried in same plot eg. family members but only one graveplot per burial record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='burials', to='bgsite.GravePlot'),
        ),
    ]
