# Generated by Django 2.1 on 2019-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0037_auto_20190918_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='burial',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
