# Generated by Django 2.1 on 2020-01-07 13:38

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0039_auto_20191107_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraveRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grave_number', models.CharField(max_length=20, null=True, validators=[main.validators.bleach_validator])),
                ('section', models.ForeignKey(blank=True, help_text='Section containing the plot.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bgsite.Section', verbose_name='Section')),
                ('subsection', models.ForeignKey(blank=True, help_text='Subsection containing the plot.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bgsite.Subsection', verbose_name='Subsection')),
            ],
        ),
        migrations.AlterField(
            model_name='graveplot',
            name='state',
            field=models.ForeignKey(blank=True, help_text='E.g. occupied, empty, full.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bgsite.GraveplotState', verbose_name='Graveplot State'),
        ),
        migrations.AlterField(
            model_name='graveplot',
            name='status',
            field=models.ForeignKey(blank=True, help_text='E.g. private, common, invalid.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bgsite.GraveplotStatus', verbose_name='Graveplot Status'),
        ),
        migrations.AlterField(
            model_name='graveplot',
            name='type',
            field=models.ForeignKey(blank=True, help_text='E.g. earthen grave, brick grave.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bgsite.GraveplotType', verbose_name='Graveplot Type'),
        ),
        migrations.AddField(
            model_name='burial',
            name='graveref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graveref_burials', to='bgsite.GraveRef', verbose_name='Grave Reference'),
        ),
        migrations.AddField(
            model_name='graveplot',
            name='graveref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graveref_graveplot', to='bgsite.GraveRef', verbose_name='Grave Reference'),
        ),
        migrations.AlterUniqueTogether(
            name='graveref',
            unique_together={('grave_number', 'section', 'subsection')},
        ),
    ]
