# Generated by Django 2.1 on 2020-01-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0041_auto_20200107_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burial',
            name='grave_number',
        ),
        migrations.AlterUniqueTogether(
            name='graveplot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='graveplot',
            name='grave_number',
        ),
        migrations.RemoveField(
            model_name='graveplot',
            name='section',
        ),
        migrations.RemoveField(
            model_name='graveplot',
            name='subsection',
        ),
    ]
