# Generated by Django 2.1 on 2020-12-18 04:44

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0047_auto_20201214_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='burial',
            name='coffin_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='burial',
            name='coffin_units',
            field=models.CharField(blank=True, choices=[('ft/in', 'Feet'), ('mtrs', 'Meters')], max_length=15, null=True, validators=[main.validators.bleach_validator], verbose_name='Coffin Units(ft/mtrs)'),
        ),
        migrations.AlterField(
            model_name='burial',
            name='depth_units',
            field=models.CharField(blank=True, choices=[('ft/in', 'Feet'), ('mtrs', 'Meters')], max_length=15, null=True, validators=[main.validators.bleach_validator], verbose_name='Depth Units(ft/mtrs)'),
        ),
    ]
