# Generated by Django 2.1 on 2021-02-04 03:39

from django.db import migrations, models
import main.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0047_auto_20201214_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonField',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('text', 'text'), ('select', 'select')], default='text', max_length=200)),
                ('options', models.TextField(blank=True, help_text='if the question type is "select," provide a comma-separated list of options for this question.', null=True)),
                ('required', models.BooleanField()),
                ('is_default', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Person Field Customization',
            },
        ),
    ]
