# Generated by Django 2.2.9 on 2021-02-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0048_auto_20201217_2344'),
        ('bgsite', '0049_auto_20210203_2239'),
    ]

    operations = [
    ]
