# Generated by Django 2.1 on 2021-02-17 01:04

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0050_merge_20210204_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='address',
        ),
        migrations.RemoveField(
            model_name='official',
            name='email',
        ),
        migrations.RemoveField(
            model_name='official',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='official',
            name='second_phone_number',
        )
    ]
