# Generated by Django 2.1 on 2021-02-24 02:59

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0051_auto_20210216_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfield',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personfield',
            name='field_form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personfield',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
