# Generated by Django 2.1 on 2021-03-03 02:53

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0052_auto_20210223_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravedeed',
            name='ownership_register',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
