# Generated by Django 2.1 on 2021-03-17 10:38

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0053_auto_20210302_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personfield',
            options={'verbose_name': 'Person Field Customisation'},
        ),
        migrations.AddField(
            model_name='official',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[main.validators.bleach_validator], verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='official',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[main.validators.bleach_validator], verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='official',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[main.validators.bleach_validator], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='official',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[main.validators.bleach_validator], verbose_name='Second Phone Number'),
        ),
    ]
