# Generated by Django 2.1 on 2021-03-31 17:49

from django.db import migrations, models, connection
from itertools import chain
import main.validators

def link_official_type(apps, schema_editor):
    """"
    Function to link main BurialOfficialType to Burial_Official
    """
    schema_name = connection.schema_name
    if schema_name != 'public':
        Deaths = apps.get_model("bgsite", "death")
        Persons = apps.get_model("bgsite", "person")
        Professions = apps.get_model("bgsite", "profession")
        Religions = apps.get_model("bgsite", "religion")
        Parishes = apps.get_model("bgsite", "parish")
        Events = apps.get_model("bgsite", "event")
        query_set = list(chain(Deaths.objects.filter(parish__isnull=False), Deaths.objects.filter(event__isnull=False),
                               Deaths.objects.filter(religion__isnull=False)))

        for death in query_set:
            if death.parish:
                death.parish_value = str(death.parish.parish)
            if death.religion:
                death.religion_value = str(death.religion.religion)
            if death.event:
                death.event_value = death.event.name
            death.save()

        for person in Persons.objects.filter(profession__isnull=False):
            person.profession_value = str(person.profession.profession)
            person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0054_auto_20210317_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='event_value',
            field=models.CharField(blank=True, help_text='Optional. Death have one related Event', max_length=100, null=True, verbose_name='War/Event related to Death'),
        ),
        migrations.AddField(
            model_name='death',
            name='parish_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parish'),
        ),
        migrations.AddField(
            model_name='death',
            name='religion_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Religion'),
        ),
        migrations.AddField(
            model_name='person',
            name='profession_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.RunPython(
            code=link_official_type,
            reverse_code=None,
            atomic=True,
        ),
    ]
