# Generated by Django 2.1 on 2021-04-12 00:38

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0056_auto_20210331_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Person age'),
        ),
        migrations.AddField(
            model_name='person',
            name='age_type',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[main.validators.bleach_validator], verbose_name='Age Type'),
        ),
    ]
