# Generated by Django 2.1 on 2021-04-30 04:17

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0057_auto_20210412_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[main.validators.bleach_validator], verbose_name='Company Name'),
        ),
    ]
