# Generated by Django 2.1 on 2021-05-01 03:03

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0058_auto_20210429_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='address',
        ),
        migrations.AddField(
            model_name='official',
            name='address',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='bgsite.Address'),
        ),
    ]
