# Generated by Django 2.2.9 on 2021-05-11 02:35

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0060_auto_20210508_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burial',
            name='burial_number',
            field=models.CharField(blank=True, help_text='Serial number of the entry in physical book', max_length=30, null=True, validators=[main.validators.bleach_validator]),
        ),
        migrations.AlterField(
            model_name='official',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='bgsite.Address'),
        ),
    ]
