# Generated by Django 2.2.9 on 2021-05-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0061_auto_20210510_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='burial',
            name='new_burial_grave',
            field=models.NullBooleanField(verbose_name='New burial grave'),
        ),
    ]
