# Generated by Django 2.2.9 on 2021-05-19 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0062_burial_new_burial_grave'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='other_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_address', to='bgsite.Address', verbose_name='Other Address'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_death',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='residence_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence_address', to='bgsite.Address', verbose_name='Residence Address'),
        ),
    ]
