# Generated by Django 2.2.9 on 2021-06-21 03:44

import bgsite.models
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0064_auto_20210519_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='file',
            field=models.FileField(default='', upload_to=bgsite.models.death_uploaded_person_pdf_path, validators=[main.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
