# Generated by Django 2.2.9 on 2021-06-29 03:02

import bgsite.models
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0065_person_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=bgsite.models.death_uploaded_person_pdf_path, validators=[main.validators.validate_file_extension]),
        ),
    ]
