# Generated by Django 2.2.9 on 2022-01-12 18:05

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0066_auto_20210629_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[main.validators.bleach_validator], verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='official',
            name='first_names',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[main.validators.bleach_validator], verbose_name='First Names'),
        ),
        migrations.AlterField(
            model_name='official',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True, validators=[main.validators.bleach_validator], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='official',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[main.validators.bleach_validator], verbose_name='Title'),
        ),
    ]
