# Generated by Django 2.2.9 on 2022-01-26 15:42

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        #('bgsite', '0068_auto_20220124_1106'),
        ('bgsite', '0067_auto_20220112_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[main.validators.bleach_validator], verbose_name='Title'),
        ),
    ]
