# Generated by Django 2.2.9 on 2022-01-26 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0069_auto_20220126_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingLocation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
