# Generated by Django 2.2.9 on 2022-03-21 14:19

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0072_auto_20220208_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='burial',
            name='coffin_comments',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[main.validators.bleach_validator], verbose_name='Additional Info about coffin'),
        ),
    ]
