# Generated by Django 2.2.9 on 2022-05-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0073_burial_coffin_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inscription_condition',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Reasonable'), (3, 'Poor')], default=1),
        ),
    ]
