# Generated by Django 2.2.9 on 2022-05-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0074_inspection_inscription_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='inscription_condition',
            new_name='inscription',
        ),
    ]
