# Generated by Django 2.2.9 on 2022-06-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0075_auto_20220530_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='topopolygon',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='geometries.TopoPolygons'),
        ),
    ]
