# Generated by Django 2.2.9 on 2022-07-06 22:59

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0076_auto_20220613_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, validators=[main.validators.bleach_validator], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='official',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[main.validators.bleach_validator], verbose_name='Title'),
        ),
    ]
