# Generated by Django 2.2.9 on 2022-08-25 19:59

from django.db import migrations

def populate_personfields(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PersonField = apps.get_model('bgsite', 'PersonField')
    people = PersonField.objects.all()
    if people.count() == 0:
        db_alias = schema_editor.connection.alias
        PersonField.objects.using(db_alias).bulk_create([
            PersonField(is_default=False, name="Burial Title", required=False, type="text"),
            PersonField(content="profession", field_form="DeathPersonDetails", is_default=False, name="Profession",
                        order=1, required=False, type="select"),
            PersonField(content="religion", field_form="DeathPersonDetails", is_default=False, name="Religion",
                        order=2, required=False, type="select"),
            PersonField(content="parish", field_form="DeathPersonDetails", is_default=False, name="Parish",
                        order=3, required=False, type="select"),
            PersonField(content="event", field_form="DeathPersonDetails", is_default=False, name="Event",
                        order=4, required=False, type="select"),
            PersonField(content="depth", field_form="BurialDetails", is_default=False, name="Depth",
                        order=1, required=False, type="select"),
        ])

class Migration(migrations.Migration):

    dependencies = [
        ('bgsite', '0077_auto_20220706_2259'),
    ]

    operations = [
        migrations.RunPython(code=populate_personfields, reverse_code=migrations.RunPython.noop),
    ]
