# Generated by Django 2.1 on 2019-06-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190409_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burialgroundsite',
            name='client',
            field=models.ForeignKey(help_text='Parent client that this site belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='main.Client'),
        ),
    ]
