# Generated by Django 2.1 on 2019-09-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190613_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_color', models.CharField(max_length=7, null=True)),
                ('site_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_preferences', to='main.SiteDetails')),
            ],
        ),
    ]
