# Generated by Django 2.1 on 2019-09-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_sitepreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='site_timezone',
            field=models.CharField(choices=[('Europe/London', 'Europe/London')], default='Europe/London', max_length=100),
        ),
    ]
