# Generated by Django 2.1 on 2019-09-27 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_sitepreferences_site_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='publicperson',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='company',
            name='last_edit_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_company_last_edit_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='last_edit_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='publicperson',
            name='last_edit_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_publicperson_last_edit_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicperson',
            name='last_edit_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_company_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicperson',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_publicperson_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
