# Generated by Django 2.1 on 2019-09-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190927_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicperson',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
