# Generated by Django 2.1 on 2019-09-30 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190927_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralDirector',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_edit_date', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retired', models.BooleanField(default=False)),
                ('bg_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('clients', models.ManyToManyField(to='main.Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_funeraldirector_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_edit_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_funeraldirector_last_edit_by', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.PublicPerson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
