# Generated by Django 2.1 on 2019-11-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20191003_1025'),
        ('main', '0023_funeraldirector'),
    ]

    operations = [
    ]
