# Generated by Django 2.1 on 2019-11-28 11:28

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_merge_20191121_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funeraldirector',
            name='bg_user',
        ),
        migrations.RemoveField(
            model_name='funeraldirector',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='funeraldirector',
            name='person',
        ),
        migrations.AddField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[main.validators.bleach_validator], verbose_name='Contact name'),
        ),
        migrations.AddField(
            model_name='funeraldirector',
            name='company',
            field=models.OneToOneField(default='2d448797-99a7-423d-8f2b-80d6c7fb3106', on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[main.validators.bleach_validator], verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='burialgroundsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_groups', to='main.BurialGroundSite'),
        ),
    ]
