# Generated by Django 2.2.9 on 2020-01-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20191128_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='public_access',
            field=models.BooleanField(default=False, help_text='If true, a restricted site will be available to the public without needing to log in.'),
        ),
    ]
