# Generated by Django 2.1 on 2020-11-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_reporttemplate'),
        ('main', '0026_sitepreferences_public_access'),
    ]

    operations = [
    ]
