# Generated by Django 2.1 on 2021-01-20 05:59

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_merge_20201124_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicperson',
            name='place_living',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[main.validators.bleach_validator]),
        ),
        migrations.AddField(
            model_name='publicperson',
            name='postcode',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[main.validators.bleach_validator]),
        ),
    ]
