# Generated by Django 2.2.9 on 2021-03-29 10:50

# Generated by Django 2.2.9 on 2021-03-28 23:07
from __future__ import unicode_literals

from django.db import migrations, models, connection

def populate_featurecode_featuregroup(apps, schema_editor):
    FeatureCode = apps.get_model("geometriespublic", "FeatureCode")
    FeatureGroup = apps.get_model("geometriespublic", "FeatureGroup")

    if connection.schema_name == 'public':
        feature_names = [{'feature_type':'sundial','display_name':'Sundial','type':'vector','min_resolution':0,
        'max_resolution':0.25,'show_in_toolbar':True,'feature_group':'furniture','hierarchy':105},]

        for name in feature_names:
            fc, created = FeatureCode.objects.get_or_create(feature_type=name['feature_type'], display_name=name['display_name'],type=name['type'],
            min_resolution=name['min_resolution'], max_resolution=name['max_resolution'], show_in_toolbar=name['show_in_toolbar'],
                hierarchy=name['hierarchy'])
            if created:
                group = FeatureGroup.objects.get(group_code=name['feature_group'])
                group.feature_codes.add(fc)



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210120_0559'),
    ]

    operations = [
        migrations.RunPython(populate_featurecode_featuregroup),
    ]
