# Generated by Django 2.2.9 on 2022-01-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_meetinglocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingLocation',
        ),
    ]
