# Generated by Django 2.2.9 on 2022-01-31 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_referencenumstyles'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteReferenceSettings',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_number', models.IntegerField(blank=True, default=1, null=True)),
                ('burialgroundsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BurialGroundSite')),
                ('ref_style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ReferenceNumStyles')),
            ],
        ),
    ]
