# Generated by Django 2.1 on 2019-05-17 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geometriespublic', '0003_auto_20190517_0904'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgsite', '0031_auto_20190404_1104'),
        ('geometries', '0008_auto_20190520_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSurveyTemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geometriespublic.FieldType')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('char_value', models.CharField(blank=True, max_length=255, null=True)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('boolean_value', models.NullBooleanField()),
                ('date_value', models.DateField(null=True)),
                ('textarea_value', models.CharField(blank=True, max_length=400, null=True)),
                ('image_value', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='bgsite.Image')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_fields', to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feature_codes', models.ManyToManyField(related_name='survey_templates', to='geometriespublic.FeatureCode')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyTemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(limit_choices_to={models.Q(models.Q(('app_label', 'surveypublic'), ('model', 'DefaultSurveyTemplateField')), models.Q(('app_label', 'survey'), ('model', 'SiteSurveyTemplateField')), _connector='OR')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='TopoPointSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
                ('topopolygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geometries.TopoPoints')),
            ],
        ),
        migrations.CreateModel(
            name='TopoPolygonSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
                ('topopolygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geometries.TopoPolygons')),
            ],
        ),
        migrations.CreateModel(
            name='TopoPolylineSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
                ('topopolygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geometries.TopoPolylines')),
            ],
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='fields',
            field=models.ManyToManyField(to='survey.SurveyTemplateField'),
        ),
        migrations.AddField(
            model_name='surveyfield',
            name='survey_template_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyTemplateField'),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyTemplate'),
        ),
    ]
