# Generated by Django 2.1 on 2019-05-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesurveytemplatefield',
            name='retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesurveytemplatefield',
            name='type',
            field=models.ForeignKey(limit_choices_to={'survey': True}, on_delete=django.db.models.deletion.CASCADE, to='geometriespublic.FieldType'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='feature_codes',
            field=models.ManyToManyField(blank=True, related_name='survey_templates', to='geometriespublic.FeatureCode'),
        ),
    ]
