# Generated by Django 2.1 on 2019-05-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190520_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveytemplatefield',
            options={'ordering': ['content_type__model', 'site_survey_template_fields__name', 'default_survey_template_fields__name']},
        ),
        migrations.RenameField(
            model_name='topopointsurvey',
            old_name='topopolygon',
            new_name='topopoint',
        ),
        migrations.RenameField(
            model_name='topopolylinesurvey',
            old_name='topopolygon',
            new_name='topopolyline',
        ),
        migrations.AddField(
            model_name='survey',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topopointsurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topopoint_surveys', to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='topopolygonsurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topopolygon_surveys', to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='topopolylinesurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topopolyline_surveys', to='survey.Survey'),
        ),
    ]
