# Generated by Django 2.1 on 2019-06-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('survey', '0003_auto_20190523_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveytemplate',
            name='fields',
        ),
        migrations.CreateModel(
            name='SurveyTemplate_Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='fields',
            field=models.ManyToManyField(through='survey.SurveyTemplate_Field', to='survey.SurveyTemplateField'),
        ),
        migrations.AlterUniqueTogether(
            name='surveytemplatefield',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddField(
            model_name='surveytemplate_field',
            name='surveytemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyTemplate'),
        ),
        migrations.AddField(
            model_name='surveytemplate_field',
            name='surveytemplatefield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyTemplateField'),
        ),
    ]
