# Generated by Django 2.1 on 2019-06-27 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190626_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveytemplatefield',
            options={'ordering': ['content_type__model', 'site_survey_template_fields__name', 'public_survey_template_fields__name']},
        ),
        migrations.AlterField(
            model_name='surveytemplate_field',
            name='surveytemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_template_fields', to='survey.SurveyTemplate'),
        ),
        migrations.AlterField(
            model_name='surveytemplate_field',
            name='surveytemplatefield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_template_fields', to='survey.SurveyTemplateField'),
        ),
        migrations.AlterField(
            model_name='surveytemplatefield',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={models.Q(models.Q(('app_label', 'surveypublic'), ('model', 'PublicSurveyTemplateField')), models.Q(('app_label', 'survey'), ('model', 'SiteSurveyTemplateField')), _connector='OR')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
